apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rainfall-app
  name: rainfall-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rainfall-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rainfall-app
    spec:
      containers:
      - image: rainfall:v3
        name: rainfall
        resources: {}
status: {}
