apiVersion: v1
kind: Service
metadata:
  labels:
    app: rainfall-app
  name: rainfall-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: rainfall-app
